### ISSUE TITLE
Connect with Code for America's Clear My Record team

### ISSUE THREAD

**Issue by themightychris** [NateV/Expungement-Generator#21]
Calling @zaksoup

**Comment by NateV** [comment]
Hi, nice to meet you

**Comment by themightychris** [comment]
Also sharing this here: https://discourse.codeforamerica.org/t/join-the-record-clearance-research-team-deadline-may-3/478

Code for America is recruiting 3-5 volunteers from local groups to help map out the situations in all 50 states, maybe someone connected to this project would have good information already on a chunk of states

**Comment by mhollander** [comment]
Chris -

I would recommend getting in touch with Carl Reynolds at Council on State
Governments.  He has surveyed the data landscape in all 50 states fairly
recently.

**Comment by zaksoup** [comment]
Hi, sorry about the delay on this. Just got back from a long PTO and still catching up. What's up?
