### ISSUE TITLE
PLSE Database (and all databses) need additional tables

### ISSUE THREAD

**Issue by mhollander** [NateV/Expungement-Generator#4]
There is a table called "court" and another called "mdjcourt" and another called "police" that has the addresses for all of teh courts in the state and all of the police in Montco.  These need to be added to the stub databse (I think) and definitely to our running PLSE instance.  Attaching the sql file in case it helps.  This is already on our instance.  THe file attached can lose the .txt extension.

To add this, you can run mysql -u user -p databasename < court_police.sql
[court_police.sql.txt](https://github.com/NateV/Expungement-Generator/files/2279258/court_police.sql.txt)

**Comment by NateV** [comment]
table's in
