### ISSUE TITLE
Phantomjs errors coming up on regular search page

### ISSUE THREAD

**Issue by mhollander** [NateV/Expungement-Generator#6]
I'll signal you a name and DOB

**Comment by mhollander** [comment]
![image](https://user-images.githubusercontent.com/1609252/43978443-461a6a08-9cb5-11e8-9c1e-88a9fa622dec.png)

**Comment by NateV** [comment]
Is this still true?

**Comment by mhollander** [comment]
yes. this is in expunge.php (or whatever that file calls).  Not lookup.php.  I just did it a second ago.

**Comment by NateV** [comment]
I think its fixed. Test when you can. casperscraping was not handling errors correctly, so I fixed that, and now I'm not seeing this problem any more.

casperscraping still might not be handling the same error propertly for non-mdj searches, though, so a future thing to keep in mind is that may need fixing.

If you think this is fixed, can you close?

**Comment by mhollander** [comment]
Seems to be fixed.
